# Generated by Django 2.1.5 on 2019-02-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(max_length=200, to='catalog.Language'),
        ),
    ]
