# Generated by Django 2.1.5 on 2019-02-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
