# Generated by Django 2.1.5 on 2019-02-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_todoitem_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='Todoinput',
            new_name='text',
        ),
    ]
