# Generated by Django 2.1.5 on 2019-02-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=999)),
                ('interest_rate', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('personal_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_corporation', models.BooleanField()),
            ],
            options={
                'ordering': ['name', 'personal_name'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_type', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_holder',
            field=models.ManyToManyField(to='acme_bank.AccountHolder'),
        ),
        migrations.AddField(
            model_name='account',
            name='acct_type',
            field=models.ForeignKey(on_delete='PROTECT', to='acme_bank.AccountType'),
        ),
    ]
