# Generated by Django 2.1.5 on 2019-02-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
