# Generated by Django 2.1.5 on 2019-02-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme_bank', '0002_auto_20190213_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_holder',
        ),
        migrations.AddField(
            model_name='account',
            name='account_holder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='acme_bank.AccountHolder'),
            preserve_default=False,
        ),
    ]
