# Generated by Django 2.1.5 on 2019-02-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_bank', '0003_auto_20190213_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_holder',
        ),
        migrations.AddField(
            model_name='account',
            name='account_holder',
            field=models.ManyToManyField(to='acme_bank.AccountHolder'),
        ),
    ]
