# Generated by Django 2.1.5 on 2019-02-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_bank', '0002_auto_20190214_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='personal_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
