# Generated by Django 2.1.5 on 2019-02-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme_bank', '0002_account_interest_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountholder',
            options={'ordering': ['surname', 'personal_name']},
        ),
    ]
