# Generated by Django 2.1.5 on 2019-02-15 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acme_bank', '0003_auto_20190214_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='accountholder',
            options={'ordering': ['name', 'personal_name']},
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Account number', primary_key=True, serialize=False),
        ),
    ]
