# Generated by Django 2.1.5 on 2019-03-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='pub_date',
            new_name='published_date',
        ),
    ]
