# Generated by Django 2.1.5 on 2019-02-08 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guess_the_number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('upper_bound', models.IntegerField()),
                ('won', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gameguess',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guess_the_number.Game'),
            preserve_default=False,
        ),
    ]
