print('Welcome to Mad libs')
adjective1 = input('Can you give me an adjective?')
print('Ok ', adjective1)
adjective2 = input(' Can you give me another adjective?')
bird = input(' Do have a favorite type of bird?')
room = input( ' Name a room in a house')
verb= input(' Can you give me a past tense verb?')
verb2=input('Can you give me a verb?')
liquid=input (' Can you give me a liquid?')
verb3=input( 'Can you give me a verb ending in ing ')
print('It was a',adjective1,',cold November day.',)
print('I woke up to the ',adjective2,'smell of', bird,'roasting in the',room,"downstairs.")
print('I',verb,"down the stairs to see if I could help",verb2,'the dinner')
print( 'So I carried a tray  with glasses full of',liquid,'into the ',verb3)