# Generated by Django 2.1.5 on 2019-02-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsection',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
