# Generated by Django 2.1.5 on 2019-02-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_labsection_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
